/**:
  ros__parameters:
    min_longitudinal_offset: 2.3
    max_longitudinal_offset: 2.8
    min_lateral_offset: -0.99
    max_lateral_offset: 0.99
    min_height_offset: 0.8
    max_height_offset: 1.3
